#! /bin/bash
function sitemap(){
    echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
    echo '<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
    echo '  <url>' >> sitemap.xml
    echo '      <loc>https://arex0.com/</loc>' >> sitemap.xml
    echo '      <lastmod>'$(ls --full-time index.html | awk '{print  $6}')'</lastmod>' >> sitemap.xml
    echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
    echo '      <priority>1</priority>' >> sitemap.xml
    echo '  </url>' >> sitemap.xml

    for dir in $(ls -l  | grep "^d" | grep -v '_' | awk '{print $9}')
    do
        for file in $(ls $dir | grep -v '^_')
        do
            if [[ -d "$dir/$file" ]]
            then
                if [[ -f "$dir/$file/index.md" ]]
                then
                    echo '  <url>' >> sitemap.xml
                    echo '      <loc>https://arex0.com/'$dir/$file'</loc>' >> sitemap.xml
                    echo '      <lastmod>'$(ls --full-time "$dir/$file/index.md" | awk '{print  $6}')'</lastmod>' >> sitemap.xml
                    echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
                    echo '      <priority>.8</priority>' >> sitemap.xml
                    echo '  </url>' >> sitemap.xml
                elif  [[ -f "$dir/$file/index.html" ]]
                then
                    echo '  <url>' >> sitemap.xml
                    echo '      <loc>https://arex0.com/'$dir/$file'</loc>' >> sitemap.xml
                    echo '      <lastmod>'$(ls --full-time "$dir/$file/index.html" | awk '{print  $6}')'</lastmod>' >> sitemap.xml
                    echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
                    echo '      <priority>.8</priority>' >> sitemap.xml
                    echo '  </url>' >> sitemap.xml
                fi
            else
                if [[  $file == "index.html" ]]
                then
                    echo '  <url>' >> sitemap.xml
                    echo '      <loc>https://arex0.com/'$dir'</loc>' >> sitemap.xml
                    echo '      <lastmod>'$(ls --full-time "$dir/$file" | awk '{print  $6}')'</lastmod>' >> sitemap.xml
                    echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
                    echo '      <priority>.5</priority>' >> sitemap.xml
                    echo '  </url>' >> sitemap.xml
                elif [[  $file == *.html ]]
                then
                    echo '  <url>' >> sitemap.xml
                    echo '      <loc>https://arex0.com/'$dir/${file%.html}'</loc>' >> sitemap.xml
                    echo '      <lastmod>'$(ls --full-time "$dir/$file" | awk '{print  $6}')'</lastmod>' >> sitemap.xml
                    echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
                    echo '      <priority>.5</priority>' >> sitemap.xml
                    echo '  </url>' >> sitemap.xml
                elif [[  $file == *.md ]]
                then
                    echo '  <url>' >> sitemap.xml
                    echo '      <loc>https://arex0.com/'$dir/${file%.md}'</loc>' >> sitemap.xml
                    echo '      <lastmod>'$(ls --full-time "$dir/$file" | awk '{print  $6}')'</lastmod>' >> sitemap.xml
                    echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
                    echo '      <priority>.5</priority>' >> sitemap.xml
                    echo '  </url>' >> sitemap.xml
                fi
            fi
        done
    done

    for file in $(ls -l link/github | grep "^d" | awk '{print $9}')
    do
        if [[ -f "link/github/$file/index.md" ]]
        then
            echo '  <url>' >> sitemap.xml
            echo '      <loc>https://arex0.com/link/github/'$file'</loc>' >> sitemap.xml
            echo '      <lastmod>'$(ls --full-time "link/github/$file/index.md" | awk '{print  $6}')'</lastmod>' >> sitemap.xml
            echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
            echo '      <priority>.5</priority>' >> sitemap.xml
            echo '  </url>' >> sitemap.xml
        elif  [[ -f "link/github/$file/README.md" ]]
        then
            echo '  <url>' >> sitemap.xml
            echo '      <loc>https://arex0.com/link/github/'$file'</loc>' >> sitemap.xml
            echo '      <lastmod>'$(ls --full-time "link/github/$file/README.md" | awk '{print  $6}')'</lastmod>' >> sitemap.xml
            echo '      <changefreq>weekly</changefreq>' >> sitemap.xml
            echo '      <priority>.5</priority>' >> sitemap.xml
            echo '  </url>' >> sitemap.xml
        fi
    done
    echo '</urlset>' >> sitemap.xml
}

function blog(){
    echo '[' > blog/list.json
    :> blog/list.dn.json
    for file in $( ls -lt blog | awk '{print  $9}' | sed '1d' | grep -v '^_' | grep '\.md')
    do
        time=$(ls --full-time "blog/$file" | awk '{print  $6}')
        sed -i "s/^modified_time: .*$/modified_time: \"$time\"/" "blog/$file"
        touch -t ${time//-}0000 "blog/$file"
        echo '{"name": "'$(sed -n -e 's/^title: "\(.*\)"$/\1/p' "blog/$file")'","description": "'$(sed -n -e 's/^description: "\(.*\)"$/\1/p' "blog/$file")'","created_time": "'$(sed -n -e 's/^created_time: "\(.*\)"$/\1/p' "blog/$file")'","path":"/blog/'${file%.md}'"}' >> blog/list.dn.json
        echo '{"name": "'$(sed -n -e 's/^title: "\(.*\)"$/\1/p' "blog/$file")'","description": "'$(sed -n -e 's/^description: "\(.*\)"$/\1/p' "blog/$file")'","created_time": "'$(sed -n -e 's/^created_time: "\(.*\)"$/\1/p' "blog/$file")'","path":"/blog/'${file%.md}'"},' >> blog/list.json
    done
    sed -i '$ s/.$//' blog/list.json
    echo ']' >> blog/list.json
}

sitemap
blog